### ISSUE TITLE
Update Message URLs to support iOS 11?

### ISSUE THREAD

**Issue by kennonb** [mailmate/omnifocus.mmbundle#5]
Hey,

Looks like iOS 11 updated the message URL structure to not work when including the `//` in the `message://` in the URL. OmniFocus on iOS (when dragging email) and with the Clip-o-tron for High Sierra has been updated to remove those `//` in the URL which allows them to work on iOS.

Example (Old, doesn't work in iOS):
message://%3c840227b7-8-qdur03p7qu7h4qm5n@ckmail4.com%3e

Example (New, does work in iOS):
message:%3c840227b7-8-qdur03p7qu7h4qm5n@ckmail4.com%3e

I tried to remove it, but it's not hyperlinking the URL correctly in the notes field, so I haven't been able to submit a PR. I figured I would ask and see if you knew a work around?

Thanks!

**Comment by freron** [comment]
Essentially there are four formats for this string:

~~~
message://%3c840227b7-8-qdur03p7qu7h4qm5n@ckmail4.com%3e
message://<840227b7-8-qdur03p7qu7h4qm5n@ckmail4.com>
message:%3c840227b7-8-qdur03p7qu7h4qm5n@ckmail4.com%3e
message:<840227b7-8-qdur03p7qu7h4qm5n@ckmail4.com>
~~~

The first one is used because it works (well, used to work) and text fields on macOS can identify them as URLs when they are right-clicked (for the context sensitive menu). The latter doesn't work for the new iOS format. I wonder if it has changed in High Sierra.

Can you manually create a link in the notes field which works correctly in OmniFocus in both High Sierra and iOS 11?

**Comment by kennonb** [comment]
So the more I look into this the stranger it is. This might just be badly broken in iOS 11. :( 

Here are a few things I've done:

1. If I allow OmniFocus to "mysteriously" auto-create the URL based on some arbitrary internal logic with the [following AppleScript in Mail.app](https://gist.github.com/kennonb/7eeedf216ebc1d108a92766620cbd509), it works in iOS. *BUT* it's because it has like three different variants of the URL linked and the one that closely resembles #3 of your links above is the one that you can tap on and it works.

2. If I clip using your existing Bundle in MailMate, then manually change the URLs text to remove the `//` from the URL. iOS will pick that up and create yet another odd, hot-linked, variant of that URL that I can click on & it will take me back to the message in iOS.

All that to say, I can't manually create a URL that works. I think this is some weird buggy junk, and I'm closing this. 😂 I'm sorry I wasted your time.

**Comment by freron** [comment]
Well, I'm guessing this is not the last time I'm going to hear about this. Thanks for investigating.
